---
name: Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Full git history is needed to get a proper list of changed files within 'super-linter'
          # and to dynamically determine the versionName from tags
          fetch-depth: 0
          fetch-tags: true

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Lint Code Base
        uses: super-linter/super-linter@v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_KOTLIN: true
          VALIDATE_YAML: true
          VALIDATE_XML: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Prepare keystore.properties
        run: ./.github/scripts/prepare-keystore-properties.sh
        env:
          KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          KEYSTORE_ENCRYPTION_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_ENCRYPTION_PASSPHRASE }}
          KEYSTORE_STORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSPHRASE }}
          KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSPHRASE }}

      - name: Build Release APK
        run: ./gradlew clean assembleRelease --no-daemon

      - name: Upload outputs artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: app/build/outputs/
          retention-days: 3

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/mapping/release/mapping.txt
